enum ACTIONS {
    SET_IMAGE = "SET_IMAGE",
    SEND_IMAGE = "SEND_IMAGE",
    SEND_SOURCE_IMAGE = "SEND_SOURCE_IMAGE",
    SEND_KP_NORM_IMAGE = "SEND_KP_NORM_IMAGE",
    CONNECT_SOCKET = 'CONNECT_SOCKET',
    DISCONNECT_SOCKET = 'DISCONNECT_SOCKET',
    RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
}

export default ACTIONS