enum ACTIONS {
    SEND_SOURCE_TO_ALL = "SEND_SOURCE_TO_ALL", 
    SEND_SOURCE_IMAGE = "SEND_SOURCE_IMAGE",
    MAKE_PICTURE = "MAKE_PICTURE",
    CONNECT_SOCKET = 'CONNECT_SOCKET',
    DISCONNECT_SOCKET = 'DISCONNECT_SOCKET',
    SET_SCREENSHOT = "SET_SCREENSHOT",
    GET_KP_NORM = "GET_KP_NORM",
    SET_IMAGE = "SET_IMAGE",
    SEND_KP_NORM_IMAGE_TO_ALL = "SEND_KP_NORM_IMAGE_TO_ALL"
}

export default ACTIONS